permalink: /:year/:month/:day/:title/

# 站点设置
title: "yingside"
email: 18679038@qq.com
description: "闫虹志的个人博客"
keywords: "yingside"

# 用户信息设置
weibo_username: yingside
github_username: yingside

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil



# 地址设置
baseurl: ""
url: "http://www.yingside.com"
# url: "http://127.0.0.1:4000"

# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed
